# Generated by Django 3.1.2 on 2020-12-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaluser',
            name='USERNAME_FIELD',
        ),
    ]
